.TH CUTEKIT 1 2023-02-27

.SH NAME
cutekit \- Operating System Development Kit.

.SH SYNOPSIS
\fBcutekit\fR \fIcommand\fR [\fIargs...\fR]
.br
\fBcutekit\fR \fIhelp\fP

.SH DESCRIPTION
This program is a package manager and build tool for Operating System 
development.

.SH COMMANDS
.SS Build Commands
.TP
\fBcutekit-run\fR(1)
Run target.
.TP
\fBcutekit-debug\fR(1)
Debug target.
.TP
\fBcutekit-build\fR(1)
Build target.
.TP
\fBcutekit-clean\fR(1)
Clean the build directory.
.TP
\fBcutekit-nuke\fR(1)
Clean the build directory and cache.
.SS Manifest Commands
.TP
\fBcutekit-list\fR(1)
List existing targets.
.TP
\fBcutekit-graph\fR(1)
Show dependency graph.
.SS "Package Commands"
.TP
\fBcutekit-install\fR(1)
Install all the external packages.
.TP
\fBcutekit-init\fR(1)
Start a new project.
.SS General Commands
.TP
\fBcutekit-help\fR(1)
Display help information.
.TP
\fBcutekit-version\fR(1)
Display current version and exit.

.SH EXIT STATUS
exits with status 0 if all operations were successfull, greater than 0 if 
errors occur.

.SH BUGS
See <https://github.com/cute-engineering/cutekit> for issues.

.SH EXAMPLES
.TP
Install and build a project
cutekit install
.br
cutekit build

.SH COPYRIGHT
Copyright \(co 2023 Cute Engineering.
.br
License MIT: <https://opensource.org/license/mit/>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.