.TH CUTEKIT\-RUN 1 2023-02-27

.SH NAME
cutekit\-run \- Run target.

.SH SYNOPSIS
\fBcutekit run\fR [\fIoptions\fR]
.br
\fBcutekit r\fR [\fIoptions\fR]

.SH DESCRIPTION

.SH OPTIONS
.TP
\fB\-\-target\fR=\fItarget\fR
Run target \fItarget\fR.

.SH EXIT STATUS
exits with status 0.

.SH BUGS
See <https://github.com/cute-engineering/cutekit> for issues.

.SH COPYRIGHT
Copyright \(co 2023 Cute Engineering.
.br
License MIT: <https://opensource.org/license/mit/>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
.BR cutekit (1)