.TH OSDK\-HELP 1 2023-02-27

.SH NAME
osdk\-help \- Display help information.

.SH SYNOPSIS
\fBosdk help\fR
.br
\fBosdk h\fR

.SH DESCRIPTION
This command display help information and exit.

.SH EXIT STATUS
exits with status 0.

.SH BUGS
See <https://github.com/cute-engineering/osdk> for issues.

.SH COPYRIGHT
Copyright \(co 2023 Cute Engineering.
.br
License MIT: <https://opensource.org/license/mit/>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
.BR osdk (1)